swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

basePath: /

paths:
  /tickets/{id}:
    get:
      operationId: src.controllers.ticket.get_one
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        "200":
          description: "Fetch a ticket by id"
  /tickets:
    get:
      operationId: src.controllers.ticket.get_many
      responses:
        "200":
          description: "Fetch all tickets"

  /tickets/create:
    post:
      operationId: src.controllers.ticket.create
      parameters:
        - in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/Ticket'
      responses:
        "200":
          description: "create a ticket"

definitions:
  Ticket:
    type: object
    required:
      - type
      - message
      - author
    properties:
      type:
        type: string
      message:
        type: string
      author:
        type: string